spring.application.name=backend
server.port=8081

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.sql.init.mode=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true

# spring.datasource.url=jdbc:postgresql://flowsense-db-of.postgres.uhserver.com:5432/flowsense_db_of
# spring.datasource.username=flow_user_of
# spring.datasource.password=LuizFlow2019*


spring.datasource.url=jdbc:postgresql://localhost:5432/flowsense_db
spring.datasource.username=flow_user
spring.datasource.password=flow_password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

spring.jpa.open-in-view=false



#Email - recovery de senha
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juviscreudo2@gmail.com
spring.mail.password=wtlf yhfz tnsq cpic

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG



#mqtt config
mqtt.broker=tcp://localhost:1883
mqtt.topic=sensor/fluxo